# Generated by Django 2.1.4 on 2018-12-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='road2baseccourse',
            new_name='road2basecourse',
        ),
        migrations.RenameField(
            model_name='table1',
            old_name='road3baseccourse',
            new_name='road3basecourse',
        ),
    ]
