# Generated by Django 2.1.4 on 2018-12-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_basedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table1',
        ),
    ]
