# Generated by Django 2.1.4 on 2018-12-09 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_school_repair_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_toilets', models.IntegerField()),
                ('female_toilets', models.IntegerField()),
                ('water_supply_status', models.IntegerField()),
                ('water_source', models.IntegerField()),
                ('septic_tank', models.IntegerField()),
                ('ramp', models.IntegerField()),
                ('warning_system', models.CharField(max_length=200)),
                ('communication_system', models.CharField(max_length=200)),
                ('comm_system_others', models.CharField(max_length=200)),
                ('power_supply', models.CharField(max_length=200)),
                ('ps_others', models.CharField(max_length=200)),
                ('water_reservior', models.IntegerField()),
                ('food_storage_system', models.IntegerField()),
                ('additional_toilet', models.IntegerField()),
                ('septik_tank_soak_well', models.IntegerField()),
                ('others', models.CharField(max_length=200)),
                ('update_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_by', models.CharField(max_length=200)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school_info')),
            ],
        ),
    ]
