# Generated by Django 2.1.4 on 2018-12-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_school_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='polder_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polder_washed_away', models.CharField(max_length=200)),
                ('polder_repaired', models.IntegerField()),
                ('polder_need_repairs', models.IntegerField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school_info')),
            ],
        ),
    ]
