# Generated by Django 2.1.4 on 2018-12-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_polder_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polder_inventory',
            name='school_id',
        ),
        migrations.DeleteModel(
            name='polder_inventory',
        ),
    ]
