# Generated by Django 2.1.4 on 2018-12-09 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181209_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='polder_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polder_washed_away', models.CharField(max_length=200)),
                ('polder_repaired', models.IntegerField()),
                ('polder_need_repairs', models.IntegerField()),
                ('update_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_by', models.CharField(max_length=200)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school_info')),
            ],
        ),
    ]
