# Generated by Django 2.1.4 on 2018-12-09 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_polder_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('road_from', models.CharField(max_length=200)),
                ('road_to', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('road_type', models.CharField(max_length=200)),
                ('road_id', models.CharField(max_length=200)),
                ('length', models.FloatField()),
                ('pavement_width', models.FloatField()),
                ('embankment_width', models.FloatField()),
                ('kachcha', models.IntegerField()),
                ('bc', models.IntegerField()),
                ('others', models.CharField(max_length=200)),
                ('surfacing', models.FloatField()),
                ('base_course', models.FloatField()),
                ('s_base', models.FloatField()),
                ('road_covered', models.FloatField()),
                ('avg_depth', models.FloatField()),
                ('update_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_by', models.CharField(max_length=200)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school_info')),
            ],
        ),
    ]
