# Generated by Django 2.1.4 on 2018-12-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_access_road'),
    ]

    operations = [
        migrations.CreateModel(
            name='environmental_screnning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_1_answer', models.IntegerField()),
                ('e_1_scale_of_impact', models.IntegerField()),
                ('e_1_remarks', models.CharField(max_length=200)),
                ('e_2_answer', models.IntegerField()),
                ('e_2_scale_of_impact', models.IntegerField()),
                ('e_2_remarks', models.CharField(max_length=200)),
                ('e_3_answer', models.IntegerField()),
                ('e_3_scale_of_impact', models.IntegerField()),
                ('e_3_remarks', models.CharField(max_length=200)),
                ('e_4_answer', models.IntegerField()),
                ('e_4_scale_of_impact', models.IntegerField()),
                ('e_4_remarks', models.CharField(max_length=200)),
                ('e_5_answer', models.IntegerField()),
                ('e_5_scale_of_impact', models.IntegerField()),
                ('e_5_remarks', models.CharField(max_length=200)),
                ('e_6_answer', models.IntegerField()),
                ('e_6_scale_of_impact', models.IntegerField()),
                ('e_6_remarks', models.CharField(max_length=200)),
                ('e_7_answer', models.IntegerField()),
                ('e_7_scale_of_impact', models.IntegerField()),
                ('e_7_remarks', models.CharField(max_length=200)),
                ('e_8_answer', models.IntegerField()),
                ('e_8_scale_of_impact', models.IntegerField()),
                ('e_8_remarks', models.CharField(max_length=200)),
                ('e_9_answer', models.IntegerField()),
                ('e_9_scale_of_impact', models.IntegerField()),
                ('e_9_remarks', models.CharField(max_length=200)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school_info')),
            ],
        ),
    ]
