# Generated by Django 2.1.4 on 2018-12-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_environmental_screnning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmental_screnning',
            name='school_id',
        ),
        migrations.DeleteModel(
            name='environmental_screnning',
        ),
    ]
