# Generated by Django 2.1.4 on 2018-12-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_environmental_screnning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedata',
            name='acc_cap_livestock',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='acc_cap_per',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='additionaltoilet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='communicationsource',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='condition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='constructionyear',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='cs_others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='distance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='district',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e1_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e1_b',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e1_c',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e2_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e2_b',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e2_c',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e3_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e3_b',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e3_c',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e4_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e4_b',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e4_c',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e5_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e5_b',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e5_c',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e6_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e6_b',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e6_c',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e7_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e7_b',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e7_c',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e8_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e8_b',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e8_c',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e9_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e9_b',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='e9_c',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='easting',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='existing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='expectedpopulation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='f_ohter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='femaletoilet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='first',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='foodstoragesystem',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='fundingagencies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='g_others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='ground',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='landarea',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='maletoilet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='mouza',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='noofvillage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='northing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='plintharea',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='polderneedrepairs',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='polderrepaired',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='polderwashedaway',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='population',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='powerstation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='ps_others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='ramp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1avgdepth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1basecourse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1bc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1embankment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1kachcha',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1length',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1pavement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1roadcovered',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1sbase',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1surfacing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road1type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2avgdepth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2basecourse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2bc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2embankment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2kachcha',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2length',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2pavement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2roadcovered',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2sbase',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2surfacing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road2type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3avgdepth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3basecourse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3bc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3embankment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3kachcha',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3length',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3pavement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3roadcovered',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3sbase',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3surfacing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road3type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4avgdepth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4basecourse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4bc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4embankment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4kachcha',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4length',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4pavement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4roadcovered',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4sbase',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4surfacing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='road4type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_beam',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_column',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_door',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_first',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_ground',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_ifothersfillup',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_ramp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_roof',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_second',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_stair',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_toilet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_wall',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='rs_window',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='s_others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='s_union',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='schoolid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='second',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='septictank',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='septiktanksoakwell',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='sheltername',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='t_others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='third',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='underconstruction',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='upazilla',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='usesas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='village',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='warningsystem',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='warningsystemdetails',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='waterreservior',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='watersupplysource',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='watersupplystatus',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='school_info',
            name='distance',
            field=models.FloatField(),
        ),
    ]
