# Generated by Django 2.1.4 on 2018-12-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181217_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedata',
            name='updated_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
